### ISSUE TITLE
Install fails for Raspian Stretch

### ISSUE THREAD

**Issue by hugo-a-garcia** [headmelted/codebuilds#88]
Hi

Installs fails on a Raspberry Pi 4 with Raspian Stretch when using the install script.

```
Installing [headmelted] repository...
Updating APT cache...
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 https://deb.nodesource.com/node_12.x buster InRelease
Get:4 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease [23,4 kB]
Err:4 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
Reading package lists...
W: GPG error: https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
E: The repository 'https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease' is not signed.
Done!
Repository install complete.
Installing Visual Studio Code from [stretch]...
Reading package lists... Done
E: The value 'stretch' is invalid for APT::Default-Release as such a release is not available in the sources
Visual Studio Code install failed.
```

**Comment by monkeycoder99** [comment]
Same result on Ubuntu 18.04 with Nvidia Jetson Xavier (arm64)

**Comment by headmelted** [comment]
THis has now been resolved (based on my own testing).  Can either of you re-attempt this and let me know if the issue is now resolved for you?

**Comment by headmelted** [comment]
Closing issue as I’m pretty confident this is resolved.  Please re-open if this is not the case.

**Comment by Xunnamius** [comment]
Same issue Ubuntu 18.04.3 bionic arm64
```
Hit:9 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease
Err:9 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
```

**Comment by canberkgurel** [comment]
Same issue on Ubuntu  18.04 LTS running on NVIDIA Nano.  

```
Installing [headmelted] repository...
Updating APT cache...
Get:1 file:/var/cuda-repo-10-0-local-10.0.326  InRelease
Ign:1 file:/var/cuda-repo-10-0-local-10.0.326  InRelease
Get:2 file:/var/visionworks-repo  InRelease
Ign:2 file:/var/visionworks-repo  InRelease
Get:3 file:/var/visionworks-sfm-repo  InRelease
Ign:3 file:/var/visionworks-sfm-repo  InRelease
Get:4 file:/var/visionworks-tracking-repo  InRelease
Ign:4 file:/var/visionworks-tracking-repo  InRelease
Get:5 file:/var/cuda-repo-10-0-local-10.0.326  Release [574 B]
Get:6 file:/var/visionworks-repo  Release [1,999 B]
Get:7 file:/var/visionworks-sfm-repo  Release [2,003 B]
Get:8 file:/var/visionworks-tracking-repo  Release [2,008 B]
Get:5 file:/var/cuda-repo-10-0-local-10.0.326  Release [574 B]
Get:6 file:/var/visionworks-repo  Release [1,999 B]
Get:7 file:/var/visionworks-sfm-repo  Release [2,003 B]
Get:8 file:/var/visionworks-tracking-repo  Release [2,008 B]
Hit:12 http://international.download.nvidia.com/jetson/repos/common r32 InRelease
Hit:14 http://international.download.nvidia.com/jetson/repos/t210 r32 InRelease
Hit:15 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Hit:16 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:17 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:19 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Get:18 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease [23.4 kB]
Err:18 https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
Reading package lists...
W: GPG error: https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8
E: The repository 'https://packagecloud.io/headmelted/codebuilds/debian stretch InRelease' is not signed.
Done!
Repository install complete.
Installing Visual Studio Code from [stretch]...
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Visual Studio Code install failed.
```

**Comment by gruijter** [comment]
same issue on rpi today
`Failed to fetch https://packagecloud.io/headmelted/codebuilds/debian/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8`

**Comment by mfreeborn** [comment]
> same issue on rpi4 (raspbian) today:
> `Failed to fetch https://packagecloud.io/headmelted/codebuilds/debian/dists/stretch/InRelease The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0CC3FD642696BFC8`
> 
> I used this script to install:
> `. <( wget -O - https://code.headmelted.com/installers/apt.sh )`
> 
> EDIT: I rebooted the pi and installed again using the above script (doing `sudo -s` first). After that it seems to install fine, and I get no errors now when doing `apt update`
> 
> Thx 4 your awesome work @headmelted !

Just to add, I re-ran the script (first doing sudo -s) and it didn't fix it. I then rebooted and reran the script a second time (using sudo -s) and the problem went away.

Raspberry Pi 4 running Ubuntu 19.10
